### ISSUE TITLE
Mcprep not working?

### ISSUE THREAD

**Issue by Megashotgaming** [TheDuckCow/MCprep#39]
So I've been trying to get Mcprep working for about a day now idk whats wrong but I followed the instructions and it won't show up in the addons section where it is supposed to be (user) thanks for your help.

**Comment by TheDuckCow** [comment]
Sorry to hear you're having troubles. Are you downloading and installing the .zip from the website page? 
http://theduckcow.com/dev/blender/mcprep-download/

If it doesn't even show up on blender, it makes me think you downloaded an invalid zip. If you *were* to unzip it, you should see the __init__ file in the main folder. Then, also try searching for MCprep in the box for addons, finally if there is an error message on enabling, screenshot and share. Make sure to be using blender 2.72 or later!

**Comment by TheDuckCow** [comment]
Following up, have you been able to resolve the issue?

**Comment by BlenderUser489** [comment]
![bandicam 2017-08-07 15-01-36-912](https://user-images.githubusercontent.com/30793607/29017568-9b635a20-7b81-11e7-9729-10783e50c449.jpg)
 why I click at the prep material and nothing happened

**Comment by TheDuckCow** [comment]
Can you please enter render mode? It modified materials, which may not be a visible change if in wireframe mode. Add a sun lamp to the scene via shift-a and then press F12 or the render button to see if it worked (or textures are non blurry)

**Comment by AidanSpr** [comment]
I installed it and i can see it in users but when i click on the little box nothing is happening. Can u please help me?

**Comment by TheDuckCow** [comment]
What do you mean by nothing happens? Does the tick box become checked without any popup errors? Or is there an error that comes up. Also check the 3d view and see if an MCprep tab appears in the T tools menu.

**Comment by AidanSpr** [comment]
No it only  not become checked

**Comment by TheDuckCow** [comment]
Sorry for the long delay - I should have said again, try entering render mode after adding a lamp. In that wireframe mode, you wouldn't see images or textures anyways.

**Comment by HyperstormPro** [comment]
My prep materials button doesn't work!!! Help plss
video here https://www.youtube.com/watch?v=esg19ASteAM

**Comment by TheDuckCow** [comment]
@HyperstormPro Hi there, you seem to be using a really old version of MCprep, please try the latest version. To install, be sure to completely remove the old version of the addon from user preferences (not just disable, but remove), close blender, reopen blender, then install v3.1.1 which is the current latest. 

The only other thing I'll add is, check that one of the materials exists with images. The new MCprep version should fix this automatically, but if you lost your textures (ie moved the obj file before importing, or didn't export textures from whichever program in the first place) then it wouldn't have worked. v3.1.1 fix this by auto re-connecting image textures where possible to those that come with MCprep.

**Comment by Minecrafter2007** [comment]
i was able to download mcprep to the blender add ons but when i go to user to tick the box as soon as i tick the box blender freezes and closes and i even restarted my laptop but it still doesnt work

**Comment by StandingPadAnimations** [comment]
Don't use 3.0, use the latest version. Also, please watch Judo's Blender 2.9 tutorial since the BPS one is outdated.

**Comment by StandingPadAnimations** [comment]
Also, use 2.92 as that's the most stable(not to mention quality of life updates) and don't worry, Judo's tutorial is still useful in 2.92

**Comment by wdkd69** [comment]
does mcprep not work on v2.93 ?

**Comment by StandingPadAnimations** [comment]
It does now in the newest version

**Comment by Imbeded** [comment]
Why wont the a player mob load?

**Comment by LavaLagends** [comment]
pls i need help Mcprep isn't Preping materials. It is saying Evee or Blender Internal (Error)

**Comment by Aspirata** [comment]
> pls i need help Mcprep isn't Preping materials. It is saying Evee or Blender Internal (Error)

https://github.com/Moo-Ack-Productions/MCprep/issues/606#issuecomment-2248598409

**Comment by StandingPadAnimations** [comment]
> pls i need help Mcprep isn't Preping materials. It is saying Evee or Blender Internal (Error)

Do not comment reports that were closed 6 years old. If you have an issue, file a new report
