### ISSUE TITLE
MCprep causes FPS drops in Blender windows.

### ISSUE THREAD

**Issue by LeozinhoO12** [TheDuckCow/MCprep#693]
### Did the issue happen after restarting Blender?

- [x] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [x] I have checked known issues, and my problem is different

### What happened?

Over time, during the animation process, MCprep randomly started causing a massive drop in FPS in Blender windows. It just happened, and I don't know why. I didn't do anything, and MCprep started experiencing huge FPS drops randomly.

Edit 1: I did some tests and discovered that MCPrep conflicts with some add-ons, Animaid, Copy Bars, and another particular add-on. I did some tests, deleting the add-on and restarting Blender, and it's always the same result. Disabling MCPrep makes all add-ons work normally, but when MCPrep is enabled, the FPS drops significantly. I thought it might be the add-ons, but it's not possible for the add-ons to work the exact moment MCPrep is disabled. In addition, MCPrep has an error message in the console:
"Failed to register scene update handler"

So I even thought it might be a problem with an addon, but 3 addons work without McPrep, and the exact moment it's activated, the FPS drops completely. My theory is: a conflict with the scene or a constant background refresh.

### What steps are needed to produce the bug?

It hasn't been discovered yet that in clean worlds without animation and NLA animations, this conflict doesn't occur. The exact moment NLA animations and keyframes in the Scene start appearing, the FPS begins to drop.

### What version of MCprep are you using?

3.6.2

### What version of Blender are you using?

Blender 4.5.X and 5.0 Beta

https://github.com/user-attachments/assets/9211f071-3c63-4111-88bd-03eff9b6d2b6

[https://youtu.be/3tvIrg-3j1s](url)

**Comment by TheDuckCow** [comment]
Thanks for sharing this, very odd indeed. I haven't seen something like this happen, but it implies there's an issue with drawing.

We just released an updated today, and there's logic that checks for updates. Maybe there is a glitch which is failing and then retrying to fetch details about the update? But regardless, I'd ask to see if it still happens after you upgrade to the latest version (and restart). If still ocurring, then It would also be helpful if you could open the system console. First, scroll down in preferences to enable Verbose logging (tick box at the bottom), then go to (inside of Blender) Window > Toggle system console, which should show a black terminal window separate to the rest of Blender. Then, share any screenshots of any errors or other messages appearing there after demonstrating the slowness. If you need, upload a zipped up text file if there's a lot of outputs.

**Comment by StandingPadAnimations** [comment]
I don't think the error message mentioned in the bug report is related. That error comes from the following section in the skin swapper:
https://github.com/Moo-Ack-Productions/MCprep/blob/b8694a1b720f6016ce7caf5e9b903eecc7795489/MCprep_addon/materials/skin.py#L810-L815

However, since Blender 2.8 removed the `scene_update_pre` handler, the error is definitely to be expected.

**Comment by LeozinhoO12** [comment]
> Thanks for sharing this, very odd indeed. I haven't seen something like this happen, but it implies there's an issue with drawing.
> 
> We just released an updated today, and there's logic that checks for updates. Maybe there is a glitch which is failing and then retrying to fetch details about the update? But regardless, I'd ask to see if it still happens after you upgrade to the latest version (and restart). If still ocurring, then It would also be helpful if you could open the system console. First, scroll down in preferences to enable Verbose logging (tick box at the bottom), then go to (inside of Blender) Window > Toggle system console, which should show a black terminal window separate to the rest of Blender. Then, share any screenshots of any errors or other messages appearing there after demonstrating the slowness. If you need, upload a zipped up text file if there's a lot of outputs.

Where is the Verbose logging? I went to preferences, but I don't know where that option is.
Furthermore, I reinstalled the addon and installed it again; it runs normally in a clean environment, but the problem persists.

**Comment by StandingPadAnimations** [comment]
Verbose logging can be found in `Preferences > Add-ons > MCprep`
<img width="572" height="28" alt="Image" src="https://github.com/user-attachments/assets/2f0ace0c-b7c6-449b-b3c3-0a3839a6b19d" />

**Comment by LeozinhoO12** [comment]
Only these messages appear, but nothing confirms an error.

Failed to register scene update handler
IMAGE_MT_uvs registration!
init
Reloading skins
Resetting sync mat cache
Resetting sync mat cache
Read blend: "E:\Blender\B_Projetos\Maquina.blend"
init
Reloading skins
Resetting sync mat cache
Resetting sync mat cache

**Comment by StandingPadAnimations** [comment]
Given there hasn't been any other reports with performance, I'm going to suspect this is related to addon conflicts, and thus close this issue. Comments can still be made here if needed, but unless someone else is able to reproduce this issue, I'll close this.
